controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - robot_arm_joint_1
      - robot_arm_joint_2
      - robot_arm_joint_3
      - robot_arm_joint_4
      - robot_arm_joint_5
      - robot_arm_joint_6
      - robot_arm_joint_7
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - robot_arm_finger_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: opened