front_left_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: robot_front_left_wheel_joint

front_left_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: robot_front_left_motor_wheel_joint

front_right_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: robot_front_right_wheel_joint

front_right_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: robot_front_right_motor_wheel_joint

back_left_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: robot_back_left_wheel_joint

back_left_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: robot_back_left_motor_wheel_joint

back_right_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: robot_back_right_wheel_joint

back_right_motor_wheel_joint_controller:
  type: position_controllers/JointPositionController
  joint: robot_back_right_motor_wheel_joint


base_controller:
  type: ackermann_drive_controller/AckermannDriveController
  traction:
    front_right:
      joint_name: robot_front_right_wheel_joint
      max_speed: 20.0 # rad/s
    front_left:
      joint_name: robot_front_left_wheel_joint
      max_speed: 20.0 # rad/s
    back_right:
      joint_name: robot_back_right_wheel_joint
      max_speed: 20.0 # rad/s
    back_left:
      joint_name: robot_back_left_wheel_joint
      max_speed: 20.0 # rad/s
  steer:
    front_right:
      joint_name: robot_front_right_motor_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    front_left:
      joint_name: robot_front_left_motor_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    back_right:
      joint_name: robot_back_right_motor_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
    back_left:
      joint_name: robot_back_left_motor_wheel_joint
      min_angle: -2.6 # rads
      max_angle: 2.6
  linear_speed_limit: 1.4
  linear_acceleration_limit: 1.0
  angular_speed_limit: 2.0
  angular_acceleration_limit: 2.0
  odom_frame: robot_odom
  robot_base_frame: robot_base_footprint
  odom_broadcast_tf: true
  odom_topic: robotnik_base_control/odom
  command_topic: robotnik_base_control/cmd_ack
  wheel_base: 1.244 #from cad
  track_width: 0.734 #from cad
  wheel_diameter: 0.31 #  from cad
  cmd_watchdog_duration: 0.2
  odom_publish_frequency: 100


joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

joint_read_command_controller:
    type: joint_read_command_controller/JointReadCommandController 
    publish_rate: 100.0

