controller_list:
  - name: "arm_controller/pos_traj_controller"
    action_ns: "follow_joint_trajectory"
    type: FollowJointTrajectory
    joints: [robot_arm_joint_1,robot_arm_joint_2,robot_arm_joint_3,robot_arm_joint_4,robot_arm_joint_5,robot_arm_joint_6]
