controller_list:
  - name: fake_arm_controller
    joints:
      - robot_arm_joint_1
      - robot_arm_joint_2
      - robot_arm_joint_3
      - robot_arm_joint_4
      - robot_arm_joint_5
      - robot_arm_joint_6
initial:  # Define initial robot poses.
  - group: arm
    pose: home