# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_arm_joint_1
    - robot_arm_joint_2
    - robot_arm_joint_3
    - robot_arm_joint_4
    - robot_arm_joint_5
    - robot_arm_joint_6
    - robot_right_finger_bottom_joint
    - robot_back_flipper_joint
    - robot_back_left_master_wheel_joint
    - robot_back_left_slave_wheel_joint
    - robot_back_left_small_wheel_1_joint
    - robot_back_left_small_wheel_2_joint
    - robot_back_left_small_wheel_3_joint
    - robot_back_right_master_wheel_joint
    - robot_back_right_slave_wheel_joint
    - robot_back_right_small_wheel_1_joint
    - robot_back_right_small_wheel_2_joint
    - robot_back_right_small_wheel_3_joint
    - robot_front_flipper_joint
    - robot_front_left_master_wheel_joint
    - robot_front_left_slave_wheel_joint
    - robot_front_left_small_wheel_1_joint
    - robot_front_left_small_wheel_2_joint
    - robot_front_left_small_wheel_3_joint
    - robot_front_right_master_wheel_joint
    - robot_front_right_slave_wheel_joint
    - robot_front_right_small_wheel_1_joint
    - robot_front_right_small_wheel_2_joint
    - robot_front_right_small_wheel_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_arm_joint_1
      - robot_arm_joint_2
      - robot_arm_joint_3
      - robot_arm_joint_4
      - robot_arm_joint_5
      - robot_arm_joint_6