front_flipper_joint_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)front_flipper_joint

front_left_master_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)front_left_master_wheel_joint

front_left_slave_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)front_left_slave_wheel_joint

front_right_master_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)front_right_master_wheel_joint

front_right_slave_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)front_right_slave_wheel_joint

back_flipper_joint_controller:
  type: position_controllers/JointPositionController
  joint: $(arg prefix)back_flipper_joint

back_left_master_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)back_left_master_wheel_joint

back_left_slave_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)back_left_slave_wheel_joint

back_right_master_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)back_right_master_wheel_joint

back_right_slave_wheel_joint_controller:
  type: velocity_controllers/JointVelocityController
  joint: $(arg prefix)back_right_slave_wheel_joint

joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0

joint_read_command_controller:
    type: joint_read_command_controller/JointReadCommandController 
    publish_rate: 100.0

# Settings for ros_control hardware interface
hardware_interface:
  joints:
     - $(arg prefix)front_flipper_joint
     - $(arg prefix)back_flipper_joint
     - $(arg prefix)front_left_master_wheel_joint
     - $(arg prefix)front_left_slave_wheel_joint
     - $(arg prefix)front_right_master_wheel_joint
     - $(arg prefix)front_right_master_wheel_joint     
     - $(arg prefix)back_left_master_wheel_joint
     - $(arg prefix)back_left_slave_wheel_joint
     - $(arg prefix)back_right_master_wheel_joint
     - $(arg prefix)back_right_master_wheel_joint 